import type { Member } from "./members.ts";
import members from "./members.ts";

const memberDict: { [key: string]: Member } = {};
const findMember = (id: string) => memberDict[id] ? memberDict[id] : id;
for (const member of members) memberDict[member.id] = member;

export interface Publication {
  id: string;
  date: string;
  type: string;
  title: string;
  authors: (string | Member)[];
  firstAuthors?: number[];
  correspondingAuthors?: number[];
  description: string;
  links?: { [key: string]: string };
}

  // Example:
  // {
  //   id: "FedMosaic",
  //   date: "2026-04-23",
  //   type: "Conference",
  //   title: "Not All Clients Are Equal: Collaborative Model Personalization on Heterogeneous Multi-Modal Clients",
  //   authors: [
  //     "Minhyuk Seo",
  //     "Taeheon Kim",
  //     "@hankook",
  //     "Jonghyun Choi",
  //     "Tinne Tuytelaars",
  //   ].map(findMember),
  //   firstAuthors: [0, 1],
  //   correspondingAuthors: [3, 4],
  //   description: [
  //     "- International Conference on Learning Representations (**ICLR**), 2026",
  //     "- Best Paper Award @ AAAI 2026 Workshop of PerFM",
  //     "- Links: [paper](https://openreview.net/forum?id=0g5Dk4Qfh0), [arxiv](https://arxiv.org/abs/2506.11024)",
  //   ].join("\n"),
  // },

const publications: Publication[] = [
  {
    id: "RDD",
    date: "2026-06-03",
    type: "Conference",
    title: "A Debiased Reconstruction-based Framework for Training-Free Detection of AI-Generated Images",
    authors: [
      "Sungik Choi",
      "@hankook",
      "Jaehoon Lee",
      "Robin Kim",
      "Jungkyu Choi",
      "Moontae Lee",
    ].map(findMember),
    description: [
      "- The IEEE/CVF Conference on Computer Vision and Pattern Recognition (**CVPR**), 2026",
    ].join("\n"),
  },
  {
    id: "SinglePrompt",
    date: "2026-06-03",
    type: "Conference",
    title: "Is Prompt Selection Necessary for Task-Free Online Continual Learning?",
    authors: [
      "@seoyoungp",
      "@haemin.lee",
      "@hankook",
    ].map(findMember),
    description: [
      "- The IEEE/CVF Conference on Computer Vision and Pattern Recognition (**CVPR Findings**), 2026",
      "- Links: [arxiv](https://arxiv.org/abs/2604.04420), [code](https://github.com/efficient-learning-lab/SinglePrompt)",
    ].join("\n"),
  },
  {
    id: "FedMosaic",
    date: "2026-04-23",
    type: "Conference",
    title: "Co-LoRA: Collaborative Model Personalization on Heterogeneous Multi-Modal Clients",
    authors: [
      "Minhyuk Seo",
      "Taeheon Kim",
      "@hankook",
      "Jonghyun Choi",
      "Tinne Tuytelaars",
    ].map(findMember),
    firstAuthors: [0, 1],
    correspondingAuthors: [3, 4],
    description: [
      "- International Conference on Learning Representations (**ICLR**), 2026",
      "- Best Paper Award @ AAAI 2026 Workshop of PerFM",
      "- Links: [paper](https://openreview.net/forum?id=0g5Dk4Qfh0), [arxiv](https://arxiv.org/abs/2506.11024)",
    ].join("\n"),
  },
  {
    id: "ReTabAD",
    date: "2026-04-23",
    type: "Conference",
    title: "ReTabAD: A Benchmark for Restoring Semantic Context in Tabular Anomaly Detection",
    authors: [
      "Sanghyu Yoon",
      "Dongmin Kim",
      "Suhee Yoon",
      "Ye Seul Sim",
      "Seungdong Yoa",
      "Hye-Seung Cho",
      "Soonyoung Lee",
      "@hankook",
      "Woohyung Lim",
    ].map(findMember),
    firstAuthors: [0, 1],
    correspondingAuthors: [7, 8],
    description: [
      "- International Conference on Learning Representations (**ICLR**), 2026",
      "- Links: [paper](https://openreview.net/forum?id=UFwgg44VZq), [arxiv](https://arxiv.org/abs/2510.02060), [code](https://github.com/yoonsanghyu/ReTabAD)",
    ].join("\n"),
  },
  {
    id: "AutoAnoEval",
    date: "2026-03-24",
    type: "Conference",
    title: "AutoAnoEval: Semantic-Aware Model Selection via Tree-Guided LLM Reasoning for Tabular Anomaly Detection",
    authors: [
      "Suhee Yoon",
      "Sanghyu Yoon",
      "Ye Seul Sim",
      "Seungdong Yoa",
      "Dongmin Kim",
      "Soonyoung Lee",
      "@hankook",
      "Woohyung Lim",
    ].map(findMember),
    correspondingAuthors: [6, 7],
    description: [
      "- Conference of the European Chapter of the Association for Computational Linguistics (**EACL Findings**), 2026"
    ].join("\n"),
  },
  {
    id: "TimePerceiver",
    date: "2025-12-02",
    type: "Conference",
    title: "TimePerceiver: An Encoder-Decoder Framework for Generalized Time-Series Forecasting",
    authors: [
      "@jaebin.lee",
      "@hankook",
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2025",
      "- Links: [paper](https://openreview.net/forum?id=RCeZ063p33), [arxiv](https://arxiv.org/abs/2512.22550), [code](https://github.com/efficient-learning-lab/TimePerceiver)",
    ].join("\n"),
  },
  {
    id: "WaRPAD",
    date: "2025-12-02",
    type: "Conference",
    title: "Training-free Detection of AI-generated images via Cropping Robustness",
    authors: [
      "Sungik Choi",
      "@hankook",
      "Moontae Lee",
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2025",
      "- Links: [paper](https://openreview.net/forum?id=UPxyTg7dTL), [arxiv](https://arxiv.org/abs/2511.14030), [code](https://github.com/sungikchoi/WaRPAD)",
    ].join("\n"),
  },
  {
    id: "RAGDefender",
    date: "2025-12-08",
    type: "Conference",
    title: "Rescuing the Unpoisoned: Efficient Defense against Knowledge Corruption Attacks on RAG Systems",
    authors: [
      "Minseok Kim",
      "@hankook",
      "Hyungjoon Koo",
    ].map(findMember),
    description: [
      "- Annual Computer Security Applications Conference (**ACSAC**), 2025",
      "- Links: [arxiv](https://arxiv.org/abs/2511.01268)",
    ].join("\n"),
  },
  {
    id: "SDOutlier",
    date: "2025-02-27",
    type: "Conference",
    title: "Diffusion-based Semantic Outlier Generation via Nuisance Awareness for Out-of-Distribution Detection",
    authors: [
      "Suhee Yoon",
      "Sanghyu Yoon",
      "Ye Seul Sim",
      "Sungik Choi",
      "Kyungeun Lee",
      "Hye-seung Cho",
      "@hankook",
      "Woohyung Lim",
    ].map(findMember),
    firstAuthors: [0, 1],
    correspondingAuthors: [6, 7],
    description: [
      "- AAAI Conference on Artificial Intelligence (**AAAI**), 2025",
      "- Links: [paper](https://ojs.aaai.org/index.php/AAAI/article/view/33427),",
      "[arxiv](https://arxiv.org/abs/2408.14841)",
    ].join("\n"),
  },
  {
    id: "EARL",
    date: "2024-06-17",
    type: "Conference",
    title: "Learning Equi-angular Representations for Online Continual Learning",
    authors: [
      "Minhyuk Seo",
      "Hyunseo Koh",
      "Wonje Jeung",
      "Min Jae Lee",
      "San Kim",
      "@hankook",
      "Sungjun Cho",
      "Sungik Choi",
      "Hyunwoo Kim",
      "Jonghyun Choi",
    ].map(findMember),
    correspondingAuthors: [8, 9],
    description: [
      "- Conference on Computer Vision and Pattern Recognition (**CVPR**), 2024",
      "- Conference on Lifelong Learning Agents (CoLLAs) Workshop, 2024",
      "- Links: [paper](https://openaccess.thecvf.com/content/CVPR2024/html/Seo_Learning_Equi-angular_Representations_for_Online_Continual_Learning_CVPR_2024_paper.html),",
      "[arxiv](https://arxiv.org/abs/2404.01628),",
      "[code](https://github.com/yonseivnl/earl)",
    ].join("\n"),
  },
  {
    id: "Holi-Mol",
    date: "2024-06-07",
    type: "Journal",
    title: "Holistic Molecular Representation Learning via Multi-view Fragmentation",
    authors: [
      "Seojin Kim",
      "Jaehyun Nam",
      "Junsu Kim",
      "@hankook",
      "Sungsoo Ahn",
      "Jinwoo Shin",
    ].map(findMember),
    firstAuthors: [0, 1],
    description: [
      "- Transactions on Machine Learning Research (**TMLR**), 2024",
      "- ICLR Workshop on Machine Learning for Materials (ML4Materials), 2023",
      "- Links: [paper](https://openreview.net/forum?id=ufDh55J1ML)",
    ].join("\n"),
  },
  {
    id: "ADP",
    date: "2024-01-16",
    type: "Journal",
    title: "Few-shot Anomaly Detection via Personalization",
    authors: [
      "Sangkyung Kwak",
      "Jongheon Jeong",
      "@hankook",
      "Woohyuck Kim",
      "Dongho Seo",
      "Woojin Yun",
      "Wonjin Lee",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- IEEE **Access**, 2024",
      "- ICML Workshop on New Frontiers in Adversarial Machine Learning (AdvML-Frontiers), 2023",
      "- Links: [paper](https://ieeexplore.ieee.org/document/10401164)",
    ].join("\n"),
  },
  {
    id: "ProjectionRegret",
    date: "2023-12-10",
    type: "Conference",
    title: "Projection Regret: Reducing Background Bias for Novelty Detection via Diffusion Models",
    authors: [
      "Sungik Choi",
      "@hankook",
      "Honglak Lee",
      "Moontae Lee"
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2023",
      "- Links: [paper](https://openreview.net/forum?id=3qHlPqzjM1),",
      "[arxiv](https://arxiv.org/abs/2312.02615)",
    ].join("\n"),
  },
  {
    id: "FPS-T",
    date: "2023-07-28",
    type: "Workshop",
    title: "Mixed-Curvature Transformers for Graph Representation Learning",
    authors: [
      "Sungjun Cho",
      "Seunghyuk Cho",
      "Sungwoo Park",
      "@hankook",
      "Honglak Lee",
      "Moontae Lee",
    ].map(findMember),
    description: [
      "- ICML Workshop on Topology, Algebra, and Geometry in Machine Learning (TAG-ML), 2023",
      "- Links: [paper](https://openreview.net/forum?id=DFnk58DwTE)",
    ].join("\n"),
  },
  {
    id: "NIB",
    date: "2023-06-18",
    type: "Conference",
    title: "Enhancing Multiple Reliability Measures via Nuisance-extended Information Bottleneck",
    authors: [
      "Jongheon Jeong",
      "Sihyun Yu",
      "@hankook",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- Computer Vision and Pattern Recognition (**CVPR**), 2023",
      "- ECCV Workshop on Out-of-distribution Generalization in Computer Vision (OOD-CV), 2022",
      "- Links: [paper](https://openaccess.thecvf.com/content/CVPR2023/html/Jeong_Enhancing_Multiple_Reliability_Measures_via_Nuisance-Extended_Information_Bottleneck_CVPR_2023_paper.html),",
      "[arxiv](https://arxiv.org/abs/2303.14096),",
      "[code](https://github.com/jh-jeong/nuisance_ib),",
      "[talk](https://www.youtube.com/watch?v=rEp1kj84j3Y),",
      "[slide](https://jh-jeong.github.io/assets/docs/2023-nib/slides.pdf),",
      "[poster](https://jh-jeong.github.io/assets/docs/2023-nib/poster.png)",
    ].join("\n"),
  },
  {
    id: "STUNT",
    date: "2023-05-01",
    type: "Conference",
    title: "STUNT: Few-shot Tabular Learning with Self-generated Tasks from Unlabeled Tables",
    authors: [
      "Jaehyun Nam",
      "Jihoon Tack",
      "Kyungmin Lee",
      "@hankook",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- International Conference on Learning Representations (**ICLR**), **Spotlight**, 2023",
      "- Samsung Humantech Paper Awards, Bronze Prize, 2023",
      "- NeurIPS Workshop on Table Representation Learning (TRL), 2022",
      "- Links: [paper](https://openreview.net/forum?id=_xlsjehDvlY),",
      "[arxiv](https://arxiv.org/abs/2303.00918),",
      "[code](https://github.com/jaehyun513/STUNT)",
    ].join("\n"),
  },
  {
    id: "PsCo",
    date: "2023-05-01",
    type: "Conference",
    title: "Unsupervised Meta-learning via Few-shot Pseudo-supervised Contrastive Learning",
    authors: [
      "Huiwon Jang",
      "@hankook",
      "Jinwoo Shin",
    ].map(findMember),
    firstAuthors: [0, 1],
    description: [
      "- International Conference on Learning Representations (**ICLR**), **Spotlight**, 2023",
      "- NeurIPS Workshop on Meta-Learning (MetaLearn), 2022",
      "- Links: [paper](https://openreview.net/forum?id=TdTGGj7fYYJ),",
      "[arxiv](https://arxiv.org/abs/2303.00996),",
      "[code](https://github.com/alinlab/PsCo)",
    ].join("\n"),
  },
  {
    id: "CLEL",
    date: "2023-05-01",
    type: "Conference",
    title: "Guiding Energy-based Models via Contrastive Latent Variables",
    authors: [
      "@hankook",
      "Jongheon Jeong",
      "Sejun Park",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- International Conference on Learning Representations (**ICLR**), **Spotlight**, 2023",
      "- NeurIPS Workshop on Self-Supervised Learning (NeurIPSW-SSL), Oral, 2022",
      "- Links: [paper](https://openreview.net/forum?id=CZmHHj9MgkP),",
      "[arxiv](https://arxiv.org/abs/2303.03023),",
      "[code](https://github.com/hankook/CLEL)",
    ].join("\n"),
  },
  {
    id: "SiMT",
    date: "2022-11-28",
    type: "Conference",
    title: "Meta-Learning with Self-Improving Momentum Target",
    authors: [
      "Jihoon Tack",
      "@hankook",
      "Jongjin Park",
      "Jaeho Lee",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2022",
      "- Links: [paper](https://openreview.net/forum?id=FCNMbF_TsKm),",
      "[arxiv](https://arxiv.org/abs/2210.05185),",
      "[slide](https://jihoontack.github.io/assets/simt_slide.pdf),",
      "[poster](https://jihoontack.github.io/assets/simt_poster.pdf),",
      "[code](https://github.com/jihoontack/SiMT)",
    ].join("\n"),
  },
  {
    id: "SelfPatch",
    date: "2022-06-19",
    type: "Conference",
    title: "Patch-level Representation Learning for Self-supervised Vision Transformers",
    authors: [
      "Sukmin Yun",
      "@hankook",
      "Jaehyung Kim",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- Computer Vision and Pattern Recognition (**CVPR**), **Oral**, 2022",
      "- Links: [paper](https://openaccess.thecvf.com/content/CVPR2022/html/Yun_Patch-Level_Representation_Learning_for_Self-Supervised_Vision_Transformers_CVPR_2022_paper.html),",
      "[arxiv](https://arxiv.org/abs/2206.07990),",
      "[poster](https://hankook.github.io/assets/poster_selfpatch.pdf),",
      "[code](https://github.com/alinlab/SelfPatch)",
    ].join("\n"),
  },
  {
    id: "AugSelf",
    date: "2021-12-06",
    type: "Conference",
    title: "Improving Transferability of Representations via Augmentation-Aware Self-Supervision",
    authors: [
      "@hankook",
      "Kibok Lee",
      "Kimin Lee",
      "Honglak Lee",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2021",
      "- ICML 2021 Workshop: Self-Supervised Learning for Reasoning and Perception",
      "- Links: [paper](https://openreview.net/forum?id=U34rQjnImpM),",
      "[arxiv](https://arxiv.org/abs/2111.09613),",
      "[slide](https://hankook.github.io/assets/AugSelf_NeurIPS2021_slide.pdf),",
      "[poster](https://hankook.github.io/assets/AugSelf_NeurIPS2021_poster.pdf),",
      "[code](https://github.com/hankook/AugSelf)",
    ].join("\n"),
  },
  {
    id: "RetCL",
    date: "2021-08-19",
    type: "Conference",
    title: "RetCL: A Selection-based Approach for Retrosynthesis via Contrastive Learning",
    authors: [
      "@hankook",
      "Sungsoo Ahn",
      "Seung-Woo Seo",
      "You Young Song",
      "Eunho Yang",
      "Sung Ju Hwang",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- International Joint Conference on Artificial Intelligence (**IJCAI**), 2021",
      "- NeurIPS Workshop for Machine Learning for Molecules, 2020",
      "- Links: [paper](https://www.ijcai.org/proceedings/2021/0368.pdf),",
      "[arxiv](https://arxiv.org/abs/2105.00795),",
      "[slide](https://hankook.github.io/assets/RetCL_IJCAI2021_slide.pdf),",
      "[poster](https://hankook.github.io/assets/RetCL_IJCAI2021_poster.pdf),",
      "[code](https://github.com/hankook/RetCL)",
    ].join("\n"),
  },
  {
    id: "SelfRetro",
    date: "2021-07-18",
    type: "Conference",
    title: "Self-Improved Retrosynthetic Planning",
    authors: [
      "Junsu Kim",
      "Sungsoo Ahn",
      "@hankook",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- International Conference on Machine Learning (**ICML**), 2021",
      "- Links: [paper](http://proceedings.mlr.press/v139/kim21b.html),",
      "[arxiv](https://arxiv.org/abs/2106.04880),",
      "[slide](https://icml.cc/media/icml-2021/Slides/10749.pdf),",
      "[poster](https://drive.google.com/file/d/1sbVoaw6eSYPK4WUxW34FNakfdwmlgcVu/view),",
      "[code](https://github.com/junsu-kim97/self_improved_retro)",
    ].join("\n"),
  },
  {
    id: "GTA",
    date: "2021-02-02",
    type: "Conference",
    title: "GTA: Graph Truncated Attention for Retrosynthesis",
    authors: [
      "Seung-Woo Seo",
      "You Young Song",
      "June Yong Yang",
      "Seohui Bae",
      "@hankook",
      "Jinwoo Shin",
      "Sung Ju Hwang",
      "Eunho Yang",
    ].map(findMember),
    firstAuthors: [0, 1],
    description: [
      "- AAAI Conference on Artificial Intelligence (**AAAI**), 2021",
      "- Links: [paper](https://ojs.aaai.org/index.php/AAAI/article/view/16131)"
    ].join("\n"),
  },
  {
    id: "GEGL",
    date: "2020-12-06",
    type: "Conference",
    title: "Guiding Deep Molecular Optimization with Genetic Exploration",
    authors: [
      "Sungsoo Ahn",
      "Junsu Kim",
      "@hankook",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- Neural Information Processing Systems (**NeurIPS**), 2020",
      "- Links: [paper](https://papers.nips.cc/paper/2020/hash/8ba6c657b03fc7c8dd4dff8e45defcd2-Abstract.html),",
      "[arxiv](https://arxiv.org/abs/2007.04897),",
      "[code](https://github.com/sungsoo-ahn/genetic-expert-guided-learning)",
    ].join("\n"),
  },
  {
    id: "SLA",
    date: "2020-07-12",
    type: "Conference",
    title: "Self-supervised Label Augmentation via Input Transformations",
    authors: [
      "@hankook",
      "Sung Ju Hwang",
      "Jinwoo Shin",
    ].map(findMember),
    description: [
      "- International Conference on Machine Learning (**ICML**), 2020",
      "- Qualcomm-KAIST Innovation Awards, 2019",
      "- Links: [paper](http://proceedings.mlr.press/v119/lee20c.html),",
      "[arxiv](https://arxiv.org/abs/1910.05872),",
      "[code](https://github.com/hankook/SLA)",
    ].join("\n"),
  },
  {
    id: "L2T-ww",
    date: "2019-06-10",
    type: "Conference",
    title: "Learning What and Where to Transfer",
    authors: [
      "Yunhun Jang",
      "@hankook",
      "Sung Ju Hwang",
      "Jinwoo Shin",
    ].map(findMember),
    firstAuthors: [0, 1],
    description: [
      "- International Conference on Machine Learning (**ICML**), 2019",
      "- Links: [paper](http://proceedings.mlr.press/v97/jang19b.html),",
      "[arxiv](https://arxiv.org/abs/1905.05901),",
      "[code](https://github.com/alinlab/L2T-ww),",
      "[slide](https://icml.cc/media/Slides/icml/2019/103(13-09-00)-13-10-05-5011-learning_what_a.pdf)",
    ].join("\n"),
    links: {
      paper: "http://proceedings.mlr.press/v97/jang19b.html",
      arxiv: "https://arxiv.org/abs/1905.05901",
      code: "https://github.com/alinlab/L2T-ww",
      slide: "https://icml.cc/media/Slides/icml/2019/103(13-09-00)-13-10-05-5011-learning_what_a.pdf",
    }
  },
];

export default publications;
